pipeline {
    agent {label 'terraform'}

    stages {
        stage('vcs'){
            steps{
                sh
                """git clone https://github.com/swathipasham7/terraform-workspace.git
                   cd terraform-workspace/
                   terraform init
                   terraform apply -auto-approve
                """
            }
        }
    }
}