pipeline {
    agent {label 'terraform'}
    stages {
        stage('vcs'){
            steps{
                git url: 'https://github.com/swathipasham7/terraform-workspace.git',
                    branch: 'main'
                }
        }
        stage('build') {
            steps {
                sh """cd EC2_loadbalancer
                      terraform init
                      terraform apply -var-file ./dev.tfvars -auto-approve"""
            }
        }
    }
}                    
                